export const order_rules_default = {
  KOR_version: 2,
  theme: "nuetral",
  status: "active",
  trade_using_limits: false,
  limitprice_decay_timeduration: 1,
  doubledown_timeduration: 60,
  max_profit_waveDeviation: 3,
  max_profit_waveDeviation_timeduration: 1440,
  timeduration: 525600,
  take_profit: 0.1,
  sellout: -0.05,
  sell_out: -0.0089,
  sell_trigbee_trigger: true,
  stagger_profits: false,
  scalp_profits: false,
  scalp_profits_timeduration: 30,
  stagger_profits_tiers: 1,
  skip_sell_trigbee_distance_frequency: 0,
  skip_buy_trigbee_distance_frequency: 0,
  ignore_trigbee_at_power: 0.01,
  ignore_trigbee_in_macdstory_tier: [],
  ignore_trigbee_in_histstory_tier: [],
  ignore_trigbee_in_vwap_range: { low_range: -0.05, high_range: 0.05 },
  take_profit_in_vwap_deviation_range: { low_range: -0.05, high_range: 0.05 },
  short_position: false,
  use_wave_guage: false,
  doubledowns_allowed: 2,
  close_order_today: false,
  close_order_today_vars: {
    last_60sec: {
      take_profit: false,
      close_order_today_allowed_timeduration: 60,
    },
    last_30min: {
      take_profit: true,
      close_order_today_allowed_timeduration: 60,
    },
    last_hr: { take_profit: true, close_order_today_allowed_timeduration: 60 },
  },
  use_margin: false,
  revisit_trade_frequency: 216000,
  close_order_today_allowed_timeduration: 60,
}

const a = {
  KOR_version: 2,
  theme: "nuetral",
  status: "active",
  trade_using_limits: false,
  limitprice_decay_timeduration: 1,
  doubledown_timeduration: 60,
  max_profit_waveDeviation: 3,
  max_profit_waveDeviation_timeduration: 1440,
  timeduration: 525600,
  take_profit: 0.1,
  sellout: -0.05,
  sell_out: -0.0089,
  sell_trigbee_trigger: true,
  stagger_profits: false,
  scalp_profits: false,
  scalp_profits_timeduration: 30,
  stagger_profits_tiers: 1,
  skip_sell_trigbee_distance_frequency: 0,
  skip_buy_trigbee_distance_frequency: 0,
  ignore_trigbee_at_power: 0.01,
  ignore_trigbee_in_macdstory_tier: [],
  ignore_trigbee_in_histstory_tier: [],
  ignore_trigbee_in_vwap_range: { low_range: -0.05, high_range: 0.05 },
  take_profit_in_vwap_deviation_range: { low_range: -0.05, high_range: 0.05 },
  short_position: false,
  use_wave_guage: false,
  doubledowns_allowed: 2,
  close_order_today: false,
  close_order_today_vars: {
    last_60sec: {
      take_profit: false,
      close_order_today_allowed_timeduration: 60,
    },
    last_30min: {
      take_profit: true,
      close_order_today_allowed_timeduration: 60,
    },
    last_hr: { take_profit: true, close_order_today_allowed_timeduration: 60 },
  },
  use_margin: false,
  revisit_trade_frequency: 216000,
  close_order_today_allowed_timeduration: 60,
}
